title: Joe Chun # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aiming to be a Junior data analyst
  <br><br>
  Expertise in R, Tableau
  <br><br>
  <a href="https://www.linkedin.com/in/jchun1213/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
